### ISSUE TITLE
10x doesn't work with FancyZones

### ISSUE THREAD

**Issue by stan680** [slynch8/10x#1085]
I don't seem to be able to position 10x windows using Microsoft's FancyZones. I tend to snap windows into specific places in my monitor with this tool and it's rare to see an application that it doesn't work with.
https://docs.microsoft.com/en-us/windows/powertoys/fancyzones

More specifically, the way I like to do it is with the option to snap to zones when holding shift and dragging a window.

**Comment by kayakakan** [comment]
Hi, I would like to add that from my experience, 10x never really responded to typical Windows gestures. I remember @slynch8 say in a livestream that he was handling the rendering of the non-client area of the window himself, which on Windows implies hit-testing the mouse on that non-client area ; basically, I believe that this may be fixed by passing the control back to the DefWindowProc after the hit-testing of the non-client area, but it may not be the source of the problem. Windows APIs are a mess, and it's difficult to know what correct string of system calls will get you the behaviour that you want.
Personally, I always use 10x fullscreen, and I only have one monitor, so this is not an issue for me. I just wanted to point out that this is not a special bug related to FancyZones, and is more attributable to how tough it is to get certain effects working on Windows(which is the very slim window frame for 10x, regardless of the Windows version you use, the look is uniform). All in all, I would consider that more of a "feature incomplete" scenario than really a bug, but that's just my opinion. Hopefully you are still able to work for the most part, and this isn't a deal breaker for you.

**Comment by stan680** [comment]
Yeah this was my intuition about what was causing this too. Thinking it through more, I've now noticed that 10x also doesn't respond to the normal Windows 10 'drag to the edge of the window to make the window take up half the space' thing either. In both this case, and with FancyZones, I can get the behaviour via Windows+<arrow key>, just not by dragging the title bar. That workaround is basically fine for me but thought it might be worth a look.

**Comment by kayakakan** [comment]
Yes, this is what I was refering to regarding the typical Windows gestures. That includes dragging the window to the top of the screen to maximize it, and also shaking it left and right to minimize all background windows; repeating that last gesture will restore all background windows to their privious positions. And this is most likely a consequence of not passing control back to DefWindowProc after the hit-testing of the non-client area, but again, it could be something more subtle. Good to know it won't bother you much. Happy coding!

**Comment by slynch8** [comment]
can you see if this works in the latest build (0.34.19)

**Comment by slynch8** [comment]
fixed (0.34.20)
