### ISSUE TITLE
in multiline select, N10X.Editor.ExecuteCommand("IndentLine") double indents last line

### ISSUE THREAD

**Issue by Phildo** [slynch8/10x#1743]
In Vim.py, lines 2205 ans 2209:
```
    elif c == ">":
        for _ in range(repeat_count):
            N10X.Editor.ExecuteCommand("IndentLine")

    elif c == "<":
        for _ in range(repeat_count):
            N10X.Editor.ExecuteCommand("UnindentLine")
```
the last line of the hilighted selection gets double indented (or double unindented)

repro: enable vim mode, hit "shift V" (to go into line hilight mode), tap "j" a few times (to go down a few lines), then hit "<" or ">" to un/indent the selection

**Comment by AliElSaleh** [comment]
I'm also experiencing this issue. this is the only issue making me not want to use the editor :(

**Comment by slynch8** [comment]
It's not happening for me. Are you on the latest vim script?
https://github.com/slynch8/10x/blob/main/PythonScripts/Vim/Vim.py

**Comment by AliElSaleh** [comment]
I wasn't, I have reinstalled 10X again and I can confirm the issue has been fixed! Funny thing to think about is, that the day i first heard about this editor and tried it, is probably the day (or day after) you guys fixed the issue and haven't bothered to check for updates since. Anyways, thank a lot!

**Comment by Phildo** [comment]
I want to make sure this issue was communicated correctly, given the situation has changed since it's been opened:

The issue is that the _command_ (`N10X.Editor.ExecuteCommand("IndentLine")`) double indents the last line when multiple lines are selected, and on its own doesn't have anything to do with the vim script.

The vim script however does _use_ the command (`<` and `>`), and so that functionality was also broken.

But then the vim script was "fixed" by adding a hack to explicitly undo the (erroneous) extra indentation, and that hack is still in place:

```
    elif c == ">":
        N10X.Editor.PushUndoGroup()
        for _ in range(repeat_count):
            N10X.Editor.ExecuteCommand("IndentLine")
        Unhilight()
        # HACK FOR BROKEN ExecuteCommand("IndentLine")
        N10X.Editor.ExecuteCommand("UnindentLine")
        # /HACK
        N10X.Editor.PopUndoGroup()
        should_save = True
```

So, did this issue get closed because the vim usage isn't broken? or did it get closed because the underlying issue was fixed (in which case we'll need to remove the hack from the vim script)?

**Comment by slynch8** [comment]
I don't remember fixing it, but it does appear to be fixed now. You can remove the vim hack.

**Comment by slynch8** [comment]
The problem is that in Visual mode it creates a new cursor for the selection. So you have the normal cursor, plus the selection cursor. And it is indenting for both. Before you do anything with the selection you need to remove the second cursor by calling `SubmitVisualModeSelection()`. The selection then needs to be restored after the indent.

This seems to work:

![image](https://github.com/slynch8/10x/assets/7141856/7aebca6e-7b2f-49ce-a1c4-c73acf503066)

**Comment by slynch8** [comment]
I've pushed this change to github
