### ISSUE TITLE
Window doesn't support all expected resize operations

### ISSUE THREAD

**Issue by MaxStriebel** [slynch8/10x#347]
- Moving the window to the right or left edge of the screen doesn't resize the window to half the screen size.
- Moving the windows to the top edge doesn't show the preview animation that the window is about to go full screen.
- Resizing the window with FancyZones in [PowerToys](https://docs.microsoft.com/en-us/windows/powertoys/) is not working.

As @slynch8 has explained in his livestream this is most likely because of the removal and consequent custom handling of the taskbar. 
While searching for ways to implement a custom taskbar while implementing the above mentioned functionalities I found this great [repository](https://github.com/rossy/borderless-window) that demonstrates how to implement a borderless window. In this demonstration they have the entire window act as a giant taskbar by reacting to the WM_LBUTTONDOWN message:

	case WM_LBUTTONDOWN:
		// Allow window dragging from any point 
		ReleaseCapture();
		SendMessageW(window, WM_NCLBUTTONDOWN, HTCAPTION, 0);
		return 0;

Perhaps this helps in finding a solution.

Best
Max

**Comment by slynch8** [comment]
Thanks, that looks like a really useful link.

**Comment by Manuzor** [comment]
Just stumbled over this while trying out 10x again (which I do from time to time). I'm using FancyZones to manage window placement using shift+mouse drag to place windows in a "fancy zone" (I guess) and 10x does not respond to that. At first I thought this might be due to 10x "swallowing" input in its `WindowProc` that is supposed to be passed to the `DefWindowProc` so global hooks can take over. However, seems like this is a more general issue as described by the OP.

**Comment by slynch8** [comment]
this should all work now (0.34.20)
