### ISSUE TITLE
parser support for nested namespaces

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#502]
```
namespace Test::Foo
{
  class Bar
  {
    void TestFunc();
  }
}
```

**Comment by dafedidi** [comment]
Hello! 

I have been using 10x for a month and I would be interested to know when this issue would be tackled. I'm trying to convince my company to use it and support it, however it's a hard sell because half the code base is using nested namespace, which is not supported. 

Thank you for your time and awesome editor!

**Comment by slynch8** [comment]
Hi, thanks for reminding me about this. I'm not sure how easy it will be but I'll try and take a look this week.

**Comment by slynch8** [comment]
It doesn't support using namespace yet
`using namespace Test::Foo;`
do you need that?

**Comment by dafedidi** [comment]
Oh wow so fast ! 
No need for using namespace at the moment. I'm trying the build right now, I will let you know how it goes.

**Comment by dafedidi** [comment]
It's working great so far and I think this issue can be closed once it's merged and published! 
Thank you for the speed and prompt answers. You definitly have one more subscriber at the very least. 
I will go and re-try to push my company towards this product and linking this ticket as well. 

Have a great day!

**Comment by slynch8** [comment]
That's great to hear 🙂. I'll get this into the next build, probably tomorrow. Have a great day too.

**Comment by slynch8** [comment]
This is in the latest build (0.30.32)
