### ISSUE TITLE
GetWorkspaceExePath broken?

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#72]
In today's build, I'm getting a blank string when calling N10X.Editor.GetWorkspaceExePath()
I can't run anything.

**Comment by slynch8** [comment]
sorry about that, I'm on it...

**Comment by slynch8** [comment]
hopefully fixed in (0.25.23). I changed the way it grabs msbuild variables in that last build. For some reason it was using the FinalOutputPath variable which doesn't seem to exist now. Now it's using TargetPath which seems to work. Hopefully that will work for you.

btw, you can use the LogWorkspaceSettings to log all build variables.

**Comment by Muzza** [comment]
N10X.Editor.GetWorkspaceExePath() is now returning the string 'FinalOutputPath'

**Comment by slynch8** [comment]
Fixed (0.26.18). Accidently broke it when I was fixing the startup stall.
