### ISSUE TITLE
eastl shared_ptr

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#82]
I noticed there is support for shared_ptr but only std::shared_ptr
What would it take to support eastl::shared_ptr, or the 'using' alias that I use?
e.g. 
```cpp
template <typename T> 
using ZSharedPtr = eastl::shared_ptr<T>;

ZSharedPtr<MyType> x;
```

**Comment by slynch8** [comment]
The way I support stl is just to create a folder with the header files and add it to the Additional Includes. These files are created by hand from the stl spec so that they are as simple as possible. Here are the files 10x has so far:
[http://puredevsoftware.com/stl.zip](http://puredevsoftware.com/stl.zip)

So to support eastl create an eastl folder with the header files and add it to the AdditionalIncludes. I'm assuming it's just the namespace that is different? If so I'll add it to 10x.

**Comment by Muzza** [comment]
It is mostly a drop-in replacement so it should be just a different namespace with all the same names.
What about my using code though? From a brief experiment I don't think that is supported either.

**Comment by slynch8** [comment]
I've added eastl in (0.26.19). Let me know if it's missing anything.

Templated using statements are not supported yet, it's on the list.
