### ISSUE TITLE
add a debug command line box at top of the window

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#939]
![image](https://user-images.githubusercontent.com/7141856/174163620-b59c2d1d-01fa-439a-8d47-6ce0c85a5248.png)

**Comment by castano** [comment]
+1
It would be nice to have a way to view the current command line string without having to go all the way to settings. A quick way to override it would also be great. In Visual Studio I use the "Command Line Arguments" plugin, which is great, but it's confusing having to switch between 10x and Visual Studio to edit command line arguments. It would be awesome to have this functionality within 10x.

**Comment by knarkowicz** [comment]
+1

This is literally the last thing which holds me from leaving VS+VAX which I used for like 15+ years and switching to 10x. I pretty frequently launch cooked builds with various arguments. In order to configure everything I have exactly such a 1600 character long text box in VS (courtesy of UnrealVS), which allows me for quick configuration before a launch. If you do it, please expose somewhere length of it, as sometimes those command lines can get pretty long.

**Comment by slynch8** [comment]
Sorry, I didn't realise this bug was still open. 

You can do this with the `View Menu -> Toolsbars -> Active Workspace Toolbar`

Also, make sure you install the 10xEditorLink Visual Studio extension `Help menu -> Install 10xEditorLink`
